# This workflow leverages GitHub's Actions docker capabilities to run builds
# and tests on platforms not available directly.
# We have multiple dimensions to test: 
# - OS Distribution
# - TLS library implementation: libress, openssl
# - libc implementations: glibc, musl
# - compiler: gcc, clang (not yet tested)

on: [push]
name: Docker builds
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Alpine Linux musl+openssl
      run: docker build . --file docker/Dockerfile.alpine --tag opensmtpd-alpine:$(date +%s)
    - name: Archlinux glibc+libressl
      run: docker build . --file docker/Dockerfile.archlinux --tag opensmtpd-archlinux:$(date +%s)
